Importing libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler

Reading Data

In [3]:
df=pd.read_csv('D:\Sigmoid Tech Test\diabetes.csv')
print('Shape of dataset: {}'.format(df.shape))
print('Columns: {}'.format(df.columns))
df.head()

Shape of dataset: (768, 9)
Columns: Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
# Finding the null values
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
# Dataset Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
# Number of Unique values in df
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

Exploratory Data Analysis
Inconsistent data detection

In [7]:
# Pregnancies may be not greater than 10
print('Total number of Womens having pregnancy > 5 :{}'.format(df[df['Pregnancies']>=5].shape[0]))
print('Mean of Pregnancies: {}'.format(int(df.Pregnancies.mean())))
df['Pregnancies']=df["Pregnancies"].apply(lambda x:int(df.Pregnancies.mean()) if x>=5 else x)

Total number of Womens having pregnancy > 5 :276
Mean of Pregnancies: 3

In [8]:
# BMI can't be less than 
print("Having BMI less than 5 : {}".format(df[df['BMI']<=5].shape[0]))
print('Mean of BMI: {}'.format(df.BMI.mean()))
df['BMI']=df["BMI"].apply(lambda x:df.BMI.mean() if x<=10 else x)

Having BMI less than 5 : 11
Mean of BMI: 31.992578124999998

In [9]:
# BMI can't be less than 
print("Having BP equals to zero : {}".format(df[df['BloodPressure']==0].shape[0]))
print('Mean of BP: {}'.format(df['BloodPressure'].mean()))
df['BloodPressure']=df["BloodPressure"].apply(lambda x:df['BloodPressure'].mean() if x==0 else x)

Having BP equals to zero : 35
Mean of BP: 69.10546875

Train Test Split

In [10]:
X=df.drop(['Outcome'],axis=1)
y=df['Outcome']
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=0)

X_train.shape, X_test.shape

((537, 8), (231, 8))

In [11]:
X_train.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Pregnancies,1.000000,0.096491,0.051244,-0.154231,-0.068577,-0.147368,-0.109424,0.348150
Glucose,0.096491,1.000000,0.206084,0.060085,0.333523,0.240004,0.125547,0.282401
BloodPressure,0.051244,0.206084,1.000000,0.000134,-0.078167,0.250647,0.014205,0.303380
SkinThickness,-0.154231,0.060085,0.000134,1.000000,0.428738,0.400532,0.181830,-0.156725
Insulin,-0.068577,0.333523,-0.078167,0.428738,1.000000,0.174416,0.192464,-0.062404
BMI,-0.147368,0.240004,0.250647,0.400532,0.174416,1.000000,0.172438,-0.004652
DiabetesPedigreeFunction,-0.109424,0.125547,0.014205,0.181830,0.192464,0.172438,1.000000,0.042145
Age,0.348150,0.282401,0.303380,-0.156725,-0.062404,-0.004652,0.042145,1.000000

Feature Scaling

In [12]:
sc=StandardScaler()
sc.fit(X_train)
X_train_scaled=sc.transform(X_train)
X_test_scaled=sc.transform(X_test)

Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train_scaled,y_train)
lr.score(X_test_scaled,y_test)

0.7705627705627706